# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0003_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
