# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0004_section_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
