# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0005_auto_20181024_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('subsribers', models.CharField(max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='section/')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Section', to='skillapp.Profile')),
            ],
        ),
    ]
