# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0007_auto_20181024_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='skillapp.Profile'),
        ),
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='question',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
