# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0008_auto_20181025_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='admin',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='admin',
            new_name='profile',
        ),
    ]
