# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0009_auto_20181025_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('answer', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skillapp.Section'),
        ),
    ]
