# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0010_auto_20181025_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
