# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0013_auto_20181026_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
